{
    "url": "https://api.github.com/repos/spack/spack/issues/14107",
    "repository_url": "https://api.github.com/repos/spack/spack",
    "labels_url": "https://api.github.com/repos/spack/spack/issues/14107/labels{/name}",
    "comments_url": "https://api.github.com/repos/spack/spack/issues/14107/comments",
    "events_url": "https://api.github.com/repos/spack/spack/issues/14107/events",
    "html_url": "https://github.com/spack/spack/issues/14107",
    "id": 536209762,
    "node_id": "MDU6SXNzdWU1MzYyMDk3NjI=",
    "number": 14107,
    "title": "Installation issue: py-llvmlite",
    "user": {
        "login": "iarspider",
        "id": 636602,
        "node_id": "MDQ6VXNlcjYzNjYwMg==",
        "avatar_url": "https://avatars.githubusercontent.com/u/636602?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/iarspider",
        "html_url": "https://github.com/iarspider",
        "followers_url": "https://api.github.com/users/iarspider/followers",
        "following_url": "https://api.github.com/users/iarspider/following{/other_user}",
        "gists_url": "https://api.github.com/users/iarspider/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/iarspider/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/iarspider/subscriptions",
        "organizations_url": "https://api.github.com/users/iarspider/orgs",
        "repos_url": "https://api.github.com/users/iarspider/repos",
        "events_url": "https://api.github.com/users/iarspider/events{/privacy}",
        "received_events_url": "https://api.github.com/users/iarspider/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 446616547,
            "node_id": "MDU6TGFiZWw0NDY2MTY1NDc=",
            "url": "https://api.github.com/repos/spack/spack/labels/build-error",
            "name": "build-error",
            "color": "ff3300",
            "default": false,
            "description": null
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 2,
    "created_at": "2019-12-11T08:15:07Z",
    "updated_at": "2019-12-11T18:05:46Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "### Steps to reproduce the issue\r\n\r\n```console\r\n$ spack spec py-llvmlite@0.29.0 ^python@2.7.16\r\n\r\nInput spec\r\n--------------------------------\r\npy-llvmlite@0.29.0\r\n    ^python@2.7.16\r\n\r\nConcretized\r\n--------------------------------\r\npy-llvmlite@0.29.0%gcc@8.3.0 arch=linux-centos7-skylake\r\n    ^binutils@2.30.0%gcc@8.3.0~gold~headers~libiberty+nls~plugins arch=linux-centos7-skylake\r\n    ^llvm@8.0.0%gcc@8.3.0~all_targets build_type=Release +clang+compiler-rt~flang~gold+internal_unwind+libcxx+link_dylib~lld~lldb~omp_tsan patches=3fa900e31763cc7ff604430b86faa4eb650048c1796ebd39db2dcf84f6168a8b +polly~python~shared_libs arch=linux-centos7-skylake\r\n        ^cmake@3.8.1%gcc@8.3.0~doc+ncurses+openssl+ownlibs patches=dd3a40d4d92f6b2158b87d6fb354c277947c776424aa03f6dc8096cf3135f5d0 ~qt arch=linux-centos7-skylake\r\n        ^perl-data-dumper@2.173%gcc@8.3.0 arch=linux-centos7-skylake\r\n            ^perl@5.16.3%gcc@8.3.0+cpanm patches=0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac +shared+threads arch=linux-centos7-skylake\r\n        ^python@2.7.16%gcc@8.3.0+bz2+ctypes+dbm+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib arch=linux-centos7-skylake\r\n            ^bzip2@1.0.6%gcc@8.3.0+shared arch=linux-centos7-skylake\r\n            ^expat@2.2.9%gcc@8.3.0~libbsd arch=linux-centos7-skylake\r\n            ^gdbm@1.10%gcc@8.3.0 arch=linux-centos7-skylake\r\n            ^gettext@0.20.1%gcc@8.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-centos7-skylake\r\n                ^libxml2@2.9.9%gcc@8.3.0~python arch=linux-centos7-skylake\r\n                    ^libiconv@2.17%gcc@8.3.0 arch=linux-centos7-skylake\r\n                    ^pkgconf@0.27.1%gcc@8.3.0 arch=linux-centos7-skylake\r\n                    ^xz@5.2.2%gcc@8.3.0 arch=linux-centos7-skylake\r\n                    ^zlib@1.2.11%gcc@8.3.0+optimize+pic+shared arch=linux-centos7-skylake\r\n                ^ncurses@5.9%gcc@8.3.0 patches=f84b2708a42777aadcc7f502a261afe10ca5646a51c1ef8b5e60d2070d926b57 ~symlinks~termlib arch=linux-centos7-skylake\r\n                ^tar@1.26%gcc@8.3.0 patches=08921fcbd732050c74ddf1de7d8ad95ffdbc09f8b4342456fa2f6a0dd02a957c,5c314db58d005043bf407abaf25eb9823b9032a22fd12a0b142d4bf548130fa4,d428578be7fb99b831eb61e53b8d88a859afe08b479a21238180899707d79ce4 arch=linux-centos7-skylake\r\n            ^libffi@3.2.1%gcc@8.3.0 arch=linux-centos7-skylake\r\n            ^openssl@1.0.2k%gcc@8.3.0+systemcerts arch=linux-centos7-skylake\r\n            ^readline@8.0%gcc@8.3.0 arch=linux-centos7-skylake\r\n            ^sqlite@3.30.1%gcc@8.3.0+column_metadata+fts~functions~rtree arch=linux-centos7-skylake\r\n    ^py-enum34@1.1.6%gcc@8.3.0 arch=linux-centos7-skylake\r\n        ^py-setuptools@41.4.0%gcc@8.3.0 arch=linux-centos7-skylake\r\n\r\n$ spack install py-llvmlite@0.29.0 ^python@2.7.16\r\n==> Error: ProcessError: Command exited with status 1:\r\n    '/mnt/build/jenkins/spack/opt/spack/linux-centos7-skylake/gcc-8.3.0/python-2.7.16-thcifv7hiw2y5pgh5isqo4oodmunmvak/bin/python2.7' '-s' 'setup.py' '--no-user-cfg' 'build'\r\n\r\n4 errors found in build log:\r\n     5     running build_ext\r\n     6     /mnt/build/jenkins/spack/opt/spack/linux-centos7-skylake/gcc-8.3.0/python-2.7.16-thcifv7hiw2y5pgh5isqo4oodmunmvak/bin/python2.7 /tmp/sftnight/spack-stage/spack-stage-py-llvmlite-0.29.0-cv4wumr6cezzghl2ckyi6ihvde7qra4v/spack-src/ffi/build.py\r\n     7     LLVM version... # static-libstdc++ avoids runtime dependencies on a\r\n     8     # particular libstdc++ version.\r\n     9     /mnt/build/jenkins/spack/lib/spack/env/gcc/g++  -shared -I/mnt/build/jenkins/spack/opt/spack/linux-centos7-skylake/gcc-8.3.0/llvm-8.0.0-xspwikircwrdgcfijzftcigniyjerfam/include -std=c++11 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-rtti -g -flto assembly.cpp b\r\n           itcode.cpp core.cpp initfini.cpp module.cpp value.cpp executionengine.cpp transforms.cpp passmanagers.cpp targets.cpp dylib.cpp linker.cpp object_file.cpp -o libllvmlite.so  -L/mnt/build/jenkins/spack/opt/spack/linux-centos7-skylake/gcc-8.3.0/llvm-8.0.0-xspwikircwrdgcfijzftcigniyjerfam/lib -flto -Wl,--ex\r\n           clude-libs=ALL -lLLVM-8\r\n     10    /cvmfs/sft.cern.ch/lcg/contrib/binutils/2.30/x86_64-centos7/bin/ld: /tmp/cc2iUoiT.ltrans0.ltrans.o: relocation R_X86_64_32 against symbol `_ZTVN4llvm11raw_ostreamE@@LLVM_8' can not be used when making a shared object; recompile with -fPIC\r\n  >> 11    /cvmfs/sft.cern.ch/lcg/contrib/binutils/2.30/x86_64-centos7/bin/ld: final link failed: Nonrepresentable section on output\r\n  >> 12    collect2: error: ld returned 1 exit status\r\n  >> 13    make: *** [libllvmlite.so] Error 1\r\n     14    8.0.0\r\n     15\r\n     16    SVML not detected\r\n     17    Traceback (most recent call last):\r\n     18      File \"/tmp/sftnight/spack-stage/spack-stage-py-llvmlite-0.29.0-cv4wumr6cezzghl2ckyi6ihvde7qra4v/spack-src/ffi/build.py\", line 168, in <module>\r\n     19        main()\r\n\r\n     ...\r\n\r\n     21        main_posix('linux', '.so')\r\n     22      File \"/tmp/sftnight/spack-stage/spack-stage-py-llvmlite-0.29.0-cv4wumr6cezzghl2ckyi6ihvde7qra4v/spack-src/ffi/build.py\", line 150, in main_posix\r\n     23        subprocess.check_call(['make', '-f', makefile])\r\n     24      File \"/mnt/build/jenkins/spack/opt/spack/linux-centos7-skylake/gcc-8.3.0/python-2.7.16-thcifv7hiw2y5pgh5isqo4oodmunmvak/lib/python2.7/subprocess.py\", line 190, in check_call\r\n     25        raise CalledProcessError(retcode, cmd)\r\n     26    subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.linux']' returned non-zero exit status 2\r\n  >> 27    error: command '/mnt/build/jenkins/spack/opt/spack/linux-centos7-skylake/gcc-8.3.0/python-2.7.16-thcifv7hiw2y5pgh5isqo4oodmunmvak/bin/python2.7' failed with exit status 1\r\n```\r\n\r\n### Platform and user environment\r\n\r\nPlease report your OS here:\r\n```commandline\r\n$ uname -a \r\nLinux 453207a49b28 3.10.0-1062.4.3.el7.x86_64 #1 SMP Wed Nov 13 23:58:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux\r\n$ lsb_release -d\r\nDescription:    CentOS Linux release 7.7.1908 (Core) \r\n``` \r\n\r\n`compilers.yaml` and `packages.yaml`: https://gist.github.com/iarspider/7a9a7685e9c93fb214b608bb85bf9f19",
    "performed_via_github_app": null
}