{
    "url": "https://api.github.com/repos/spack/spack/issues/14796",
    "repository_url": "https://api.github.com/repos/spack/spack",
    "labels_url": "https://api.github.com/repos/spack/spack/issues/14796/labels{/name}",
    "comments_url": "https://api.github.com/repos/spack/spack/issues/14796/comments",
    "events_url": "https://api.github.com/repos/spack/spack/issues/14796/events",
    "html_url": "https://github.com/spack/spack/pull/14796",
    "id": 561234841,
    "node_id": "MDExOlB1bGxSZXF1ZXN0MzcyMDgzMTA1",
    "number": 14796,
    "title": "patch aws-parallelcluster so that it doesn't require enum34",
    "user": {
        "login": "adamjstewart",
        "id": 12021217,
        "node_id": "MDQ6VXNlcjEyMDIxMjE3",
        "avatar_url": "https://avatars.githubusercontent.com/u/12021217?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/adamjstewart",
        "html_url": "https://github.com/adamjstewart",
        "followers_url": "https://api.github.com/users/adamjstewart/followers",
        "following_url": "https://api.github.com/users/adamjstewart/following{/other_user}",
        "gists_url": "https://api.github.com/users/adamjstewart/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/adamjstewart/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/adamjstewart/subscriptions",
        "organizations_url": "https://api.github.com/users/adamjstewart/orgs",
        "repos_url": "https://api.github.com/users/adamjstewart/repos",
        "events_url": "https://api.github.com/users/adamjstewart/events{/privacy}",
        "received_events_url": "https://api.github.com/users/adamjstewart/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 446630669,
            "node_id": "MDU6TGFiZWw0NDY2MzA2Njk=",
            "url": "https://api.github.com/repos/spack/spack/labels/dependencies",
            "name": "dependencies",
            "color": "c2e0c6",
            "default": false,
            "description": null
        },
        {
            "id": 620268714,
            "node_id": "MDU6TGFiZWw2MjAyNjg3MTQ=",
            "url": "https://api.github.com/repos/spack/spack/labels/patch",
            "name": "patch",
            "color": "5319e7",
            "default": false,
            "description": null
        }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 4,
    "created_at": "2020-02-06T19:55:18Z",
    "updated_at": "2020-02-07T17:20:25Z",
    "closed_at": "2020-02-07T17:20:20Z",
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "pull_request": {
        "url": "https://api.github.com/repos/spack/spack/pulls/14796",
        "html_url": "https://github.com/spack/spack/pull/14796",
        "diff_url": "https://github.com/spack/spack/pull/14796.diff",
        "patch_url": "https://github.com/spack/spack/pull/14796.patch"
    },
    "body": "When I try to run `pcluster configure` with Python 3.7.6, I get the following error:\r\n```\r\n$ pcluster configure\r\nTraceback (most recent call last):\r\n  File \"/Users/Adam/.spack/darwin/.spack-env/view/bin/pcluster\", line 7, in <module>\r\n    from pkg_resources import load_entry_point\r\n  File \"/Users/Adam/.spack/darwin/.spack-env/view/lib/python3.7/site-packages/pkg_resources/__init__.py\", line 3250, in <module>\r\n    @_call_aside\r\n  File \"/Users/Adam/.spack/darwin/.spack-env/view/lib/python3.7/site-packages/pkg_resources/__init__.py\", line 3234, in _call_aside\r\n    f(*args, **kwargs)\r\n  File \"/Users/Adam/.spack/darwin/.spack-env/view/lib/python3.7/site-packages/pkg_resources/__init__.py\", line 3263, in _initialize_master_working_set\r\n    working_set = WorkingSet._build_master()\r\n  File \"/Users/Adam/.spack/darwin/.spack-env/view/lib/python3.7/site-packages/pkg_resources/__init__.py\", line 583, in _build_master\r\n    ws.require(__requires__)\r\n  File \"/Users/Adam/.spack/darwin/.spack-env/view/lib/python3.7/site-packages/pkg_resources/__init__.py\", line 900, in require\r\n    needed = self.resolve(parse_requirements(requirements))\r\n  File \"/Users/Adam/.spack/darwin/.spack-env/view/lib/python3.7/site-packages/pkg_resources/__init__.py\", line 786, in resolve\r\n    raise DistributionNotFound(req, requirers)\r\npkg_resources.DistributionNotFound: The 'enum34>=1.1.6' distribution was not found and is required by aws-parallelcluster\r\n```\r\nIt seems `enum34` is required even for Python 3.4+, where it is a builtin library.\r\n\r\n@sean-smith @demartinofra @enrico-usai @lukeseawalker @rexcsn @ddeidda @tilne I wonder if it would be possible to use the builtin enum module in Python 3.4+ so the extra dependency wouldn't be required.",
    "performed_via_github_app": null
}