{
    "url": "https://api.github.com/repos/spack/spack/issues/3274",
    "repository_url": "https://api.github.com/repos/spack/spack",
    "labels_url": "https://api.github.com/repos/spack/spack/issues/3274/labels{/name}",
    "comments_url": "https://api.github.com/repos/spack/spack/issues/3274/comments",
    "events_url": "https://api.github.com/repos/spack/spack/issues/3274/events",
    "html_url": "https://github.com/spack/spack/issues/3274",
    "id": 210891768,
    "node_id": "MDU6SXNzdWUyMTA4OTE3Njg=",
    "number": 3274,
    "title": "Unable to build Boost with Python 3",
    "user": {
        "login": "adamjstewart",
        "id": 12021217,
        "node_id": "MDQ6VXNlcjEyMDIxMjE3",
        "avatar_url": "https://avatars.githubusercontent.com/u/12021217?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/adamjstewart",
        "html_url": "https://github.com/adamjstewart",
        "followers_url": "https://api.github.com/users/adamjstewart/followers",
        "following_url": "https://api.github.com/users/adamjstewart/following{/other_user}",
        "gists_url": "https://api.github.com/users/adamjstewart/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/adamjstewart/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/adamjstewart/subscriptions",
        "organizations_url": "https://api.github.com/users/adamjstewart/orgs",
        "repos_url": "https://api.github.com/users/adamjstewart/repos",
        "events_url": "https://api.github.com/users/adamjstewart/events{/privacy}",
        "received_events_url": "https://api.github.com/users/adamjstewart/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 446616547,
            "node_id": "MDU6TGFiZWw0NDY2MTY1NDc=",
            "url": "https://api.github.com/repos/spack/spack/labels/build-error",
            "name": "build-error",
            "color": "ff3300",
            "default": false,
            "description": null
        }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 4,
    "created_at": "2017-02-28T20:14:50Z",
    "updated_at": "2017-03-03T00:36:11Z",
    "closed_at": "2017-03-03T00:36:11Z",
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "body": "I'm trying to build Boost 1.63.0 with Python 3.6.0, but it is failing. The build output contains lines like:\r\n```\r\n./boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory\r\n # include <pyconfig.h>\r\n                       ^\r\ncompilation terminated.\r\n```\r\nMy `user-config.jam` looks like:\r\n```\r\nusing gcc : : /blues/gpfs/home/software/spack-0.10.0/lib/spack/env/gcc/g++ ;\r\nusing python : 3.6 : /blues/gpfs/home/software/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-6.1.0/python-3.6.0-prk6gk3ufbfetjc2bthqokmkjtjnce3j/bin/python : /blues/gpfs/home/software/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-6.1.0/python-3.6.0-prk6gk3ufbfetjc2bthqokmkjtjnce3j/include/python3.6m :  ;\r\n```\r\n`/blues/gpfs/home/software/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-6.1.0/python-3.6.0-prk6gk3ufbfetjc2bthqokmkjtjnce3j/include/python3.6m` does indeed contain `pyconfig.h`, so I'm surprised by this error message. Anyone ever built Boost with Python 3 before?",
    "performed_via_github_app": null
}