{
    "url": "https://api.github.com/repos/spack/spack/issues/7731",
    "repository_url": "https://api.github.com/repos/spack/spack",
    "labels_url": "https://api.github.com/repos/spack/spack/issues/7731/labels{/name}",
    "comments_url": "https://api.github.com/repos/spack/spack/issues/7731/comments",
    "events_url": "https://api.github.com/repos/spack/spack/issues/7731/events",
    "html_url": "https://github.com/spack/spack/issues/7731",
    "id": 313436455,
    "node_id": "MDU6SXNzdWUzMTM0MzY0NTU=",
    "number": 7731,
    "title": "Unhelpful error message in case of misformed token",
    "user": {
        "login": "healther",
        "id": 4048699,
        "node_id": "MDQ6VXNlcjQwNDg2OTk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/4048699?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/healther",
        "html_url": "https://github.com/healther",
        "followers_url": "https://api.github.com/users/healther/followers",
        "following_url": "https://api.github.com/users/healther/following{/other_user}",
        "gists_url": "https://api.github.com/users/healther/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/healther/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/healther/subscriptions",
        "organizations_url": "https://api.github.com/users/healther/orgs",
        "repos_url": "https://api.github.com/users/healther/repos",
        "events_url": "https://api.github.com/users/healther/events{/privacy}",
        "received_events_url": "https://api.github.com/users/healther/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 509628729,
            "node_id": "MDU6TGFiZWw1MDk2Mjg3Mjk=",
            "url": "https://api.github.com/repos/spack/spack/labels/error-messages",
            "name": "error-messages",
            "color": "f9d0c4",
            "default": false,
            "description": null
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 2,
    "created_at": "2018-04-11T18:24:57Z",
    "updated_at": "2019-01-25T22:52:34Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "Summary:\r\n```\r\n$ git diff\r\ndiff --git a/var/spack/repos/builtin/packages/libtool/package.py b/var/spack/repos/builtin/packages/libtool/package.py\r\nindex 98be32a60..1d3ef4735 100644\r\n--- a/var/spack/repos/builtin/packages/libtool/package.py\r\n+++ b/var/spack/repos/builtin/packages/libtool/package.py\r\n@@ -34,7 +34,7 @@ class Libtool(AutotoolsPackage):\r\n     version('2.4.6', 'addf44b646ddb4e3919805aa88fa7c5e')\r\n     version('2.4.2', 'd2f3b7d4627e69e13514a40e72a24d50')\r\n \r\n-    depends_on('m4@1.4.6:', type='build')\r\n+    depends_on('m4@:1.4.6:', type='build')\r\n \r\n     build_directory = 'spack-build'\r\n \r\n$ spack info libtool\r\n==> Error: Unexpected token\r\n```\r\n\r\n### Expected Result\r\n\r\nAn error helping me find out where the typo is in the `package.py`\r\n\r\nI went down (or more precisely tried to go down) the rabbit hole of `spec.py`, `parse.py` and `error.py` but still don't completely understand how the error handling there is supposed to happen. When I do a \r\n```\r\n$ spack -d info libtool\r\n```\r\nI even get a \r\n```\r\nDuring handling of the above exception, another exception occurred:\r\n```\r\n\r\nI have a stop-gap measure that at least prints the token where the error occurs in #7730, but I didn't find a way to add the file that was being handled to the output. Still with `grep` and some searching I guess the user can now find the error... \r\n\r\nThis should probably be cleaned up in a more comprehensive way though (especially the \"exception while handling an exception\" part).",
    "performed_via_github_app": null
}