{
    "url": "https://api.github.com/repos/spack/spack/issues/9149",
    "repository_url": "https://api.github.com/repos/spack/spack",
    "labels_url": "https://api.github.com/repos/spack/spack/issues/9149/labels{/name}",
    "comments_url": "https://api.github.com/repos/spack/spack/issues/9149/comments",
    "events_url": "https://api.github.com/repos/spack/spack/issues/9149/events",
    "html_url": "https://github.com/spack/spack/issues/9149",
    "id": 356014341,
    "node_id": "MDU6SXNzdWUzNTYwMTQzNDE=",
    "number": 9149,
    "title": "External packages cannot access dependencies in spec",
    "user": {
        "login": "adamjstewart",
        "id": 12021217,
        "node_id": "MDQ6VXNlcjEyMDIxMjE3",
        "avatar_url": "https://avatars.githubusercontent.com/u/12021217?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/adamjstewart",
        "html_url": "https://github.com/adamjstewart",
        "followers_url": "https://api.github.com/users/adamjstewart/followers",
        "following_url": "https://api.github.com/users/adamjstewart/following{/other_user}",
        "gists_url": "https://api.github.com/users/adamjstewart/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/adamjstewart/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/adamjstewart/subscriptions",
        "organizations_url": "https://api.github.com/users/adamjstewart/orgs",
        "repos_url": "https://api.github.com/users/adamjstewart/repos",
        "events_url": "https://api.github.com/users/adamjstewart/events{/privacy}",
        "received_events_url": "https://api.github.com/users/adamjstewart/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 73908754,
            "node_id": "MDU6TGFiZWw3MzkwODc1NA==",
            "url": "https://api.github.com/repos/spack/spack/labels/bug",
            "name": "bug",
            "color": "fc2929",
            "default": true,
            "description": null
        },
        {
            "id": 455855856,
            "node_id": "MDU6TGFiZWw0NTU4NTU4NTY=",
            "url": "https://api.github.com/repos/spack/spack/labels/external-packages",
            "name": "external-packages",
            "color": "c5def5",
            "default": false,
            "description": null
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 8,
    "created_at": "2018-08-31T14:57:02Z",
    "updated_at": "2019-07-17T20:52:28Z",
    "closed_at": null,
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "body": "I'm trying to register `py-numpy` as an external package, but when I try to install it, it crashes saying that `python` is not in the spec.\r\n\r\n### Steps to reproduce the issue\r\n\r\n1. Register `py-numpy` as an external package\r\n2. Install `py-numpy`\r\n\r\n### Error Message\r\n\r\n```console\r\n$ spack --debug install py-numpy\r\n==> py-numpy@1.14.2 : has external module in bwpy/1.2.4\r\n==> py-numpy@1.14.2 : is actually installed in /opt/bwpy\r\n==> py-numpy@1.14.2 : generating module file\r\nTraceback (most recent call last):\r\n  File \"/u/sciteam/stewart1/spack/bin/spack\", line 54, in <module>\r\n    sys.exit(spack.main.main())\r\n  File \"/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/main.py\", line 653, in main\r\n    return _invoke_command(command, parser, args, unknown)\r\n  File \"/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/main.py\", line 432, in _invoke_command\r\n    return_val = command(parser, args)\r\n  File \"/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/cmd/install.py\", line 273, in install\r\n    install_spec(args, kwargs, spec)\r\n  File \"/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/cmd/install.py\", line 154, in install_spec\r\n    spec.package.do_install(**kwargs)\r\n  File \"/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/package.py\", line 1380, in do_install\r\n    return self._process_external_package(explicit)\r\n  File \"/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/package.py\", line 1302, in _process_external_package\r\n    spack.hooks.post_install(self.spec)\r\n  File \"/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/hooks/__init__.py\", line 73, in __call__\r\n    hook(*args, **kwargs)\r\n  File \"/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/hooks/module_file_generation.py\", line 48, in <lambda>\r\n    post_install = lambda spec: _for_each_enabled(spec, 'write')\r\n  File \"/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/hooks/module_file_generation.py\", line 41, in _for_each_enabled\r\n    getattr(generator, method_name)()\r\n  File \"/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/modules/common.py\", line 698, in write\r\n    context = self.context.to_dict()\r\n  File \"/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/tengine.py\", line 86, in to_dict\r\n    d = [(name, getattr(self, name)) for name in self.context_properties]\r\n  File \"/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/modules/common.py\", line 553, in environment_modifications\r\n    self.spec.package.setup_environment(_, env)\r\n  File \"/mnt/a/u/sciteam/stewart1/spack/var/spack/repos/builtin/packages/py-numpy/package.py\", line 159, in setup_environment\r\n    \r\n  File \"/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/spec.py\", line 2817, in __getitem__\r\n    raise KeyError(\"No spec with name %s in %s\" % (name, self))\r\nKeyError: 'No spec with name python in py-numpy@1.14.2%cce@8.4.6+blas+lapack arch=cray-cnl5-interlagos'\r\n```\r\nThe problem is that the `py-numpy` package contains the following `setup_environment`:\r\n```python\r\n    def setup_environment(self, spack_env, run_env):\r\n        python_version = self.spec['python'].version.up_to(2)\r\n\r\n        include_path = join_path(\r\n            self.prefix.lib,\r\n            'python{0}'.format(python_version),\r\n            'site-packages',\r\n            'numpy/core/include')\r\n\r\n        run_env.prepend_path('CPATH', include_path)\r\n```\r\nWhen creating a module file, Spack queries the `python` version. But dependencies don't seem to make it into the `spec` for external packages, causing the `KeyError`.\r\n\r\n@alalazo ",
    "performed_via_github_app": null
}